---
language: python
python: "2.7"

sudo: required
dist: trusty

env:
- ANSIBLE_LIBRARY=/home/travis/build/suzuki-shunsuke/ansible-go-module

addons:
  apt:
    sources:
    - sourceline: ppa:ansible/ansible
    packages:
    - ansible

before_script:
- ansible --version
- ansible-galaxy install -r roles.yml

script:
- ansible-playbook test.yml

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
